"""
Django settings for project_config project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import logging.config  # For potential logging setup later
import os
from pathlib import Path

import dj_database_url
import dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

PROJECT_ROOT = BASE_DIR.parent # Points to the 'omnicore-ai-platform' root directory

# --- Load Environment Variables ---
# Load .env file from the project root directory
ENV_FILE_PATH = PROJECT_ROOT / '.env'
if ENV_FILE_PATH.is_file():
    print(f"INFO: Loading environment variables from: {ENV_FILE_PATH}")
    dotenv.load_dotenv(dotenv_path=ENV_FILE_PATH)
else:
    print(f"WARNING: .env file not found at {ENV_FILE_PATH}. Using default settings or environment variables.")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', '!!!replace_this_with_a_default_only_for_local_dev_if_env_missing!!!')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'False').lower() in ('true', '1', 't')

ALLOWED_HOSTS_STRING = os.getenv('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1')
ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS_STRING.split(',') if host.strip()]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-Party Apps
    'rest_framework',        # Django REST Framework for APIs
    'corsheaders',
    'django_celery_beat', # Add this for scheduled tasks
    # For handling Cross-Origin Resource Sharing

    'apps.api',
    'apps.core',
    'apps.services',

    # Feature Apps
    'apps.features.journal',
    'apps.features.uploader',
    'apps.features.youtube'
]

MIDDLEWARE = [
    # CORS Middleware should be placed high, especially before CommonMiddleware
    'corsheaders.middleware.CorsMiddleware',

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project_config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project_config.wsgi.application'


# --- Database Configuration ---
# https://docs.djangoproject.com/en/stable/ref/settings/#databases
# Uses dj-database-url to parse DATABASE_URL from .env
DATABASE_URL = os.getenv('DATABASE_URL')

if DATABASE_URL:
    print("INFO: Configuring database using DATABASE_URL from environment.")
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600, # Optional: connection pooling duration
            # Set ssl_require based on env var if needed for production managed DBs
            ssl_require=os.getenv('DB_SSL_REQUIRE', 'False').lower() in ('true', '1', 't')
        )
    }
else:
    # Fallback to SQLite only if DATABASE_URL is not set (for initial local setup without Docker/DB)
    # WARNING: This should NOT be used when running with Docker Compose setup as defined.
    print("WARNING: DATABASE_URL not set in environment. Falling back to SQLite3.")
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3', # Creates db file in 'backend' dir
        }
    }



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# --- Internationalization ---
# https://docs.djangoproject.com/en/stable/topics/i18n/
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True # Use timezone-aware datetimes


# --- Static files (CSS, JavaScript, Images) ---
# https://docs.djangoproject.com/en/stable/howto/static-files/
STATIC_URL = 'static/'
# Define STATIC_ROOT for collectstatic if you serve Django admin static files
# STATIC_ROOT = BASE_DIR / 'staticfiles_collected'


# --- Default primary key field type ---
# https://docs.djangoproject.com/en/stable/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


DEBUG = True
SECRET_KEY = 'django-insecure-a-temporary-secret-key-for-development' # A placeholder is fine for now
ALLOWED_HOSTS = ['*'] # Allows any host/IP address


# --- CORS (Cross-Origin Resource Sharing) Settings ---
# This single line allows any website to make requests to your API.
# It is the master switch for allowing all origins.
CORS_ALLOW_ALL_ORIGINS = True

# We still define CORS_ALLOWED_ORIGINS as an empty list to prevent the NameError.
# The `django-cors-headers` library will ignore this list because
# CORS_ALLOW_ALL_ORIGINS is set to True.
CORS_ALLOWED_ORIGINS = []

# This setting is separate and should usually be True
CORS_ALLOW_CREDENTIALS = True

# --- Logging Configuration (Basic Example - Customize as needed) ---
# Simplest logging to console
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO', # Change to DEBUG for more verbose output
    },
    # Example: Quieter logging for noisy libraries
    # 'loggers': {
    #     'docker': {
    #         'handlers': ['console'],
    #         'level': 'INFO', # Docker library can be verbose on DEBUG
    #         'propagate': False,
    #     },
    # }
}

# Configure logging based on the settings dictionary
logging.config.dictConfig(LOGGING)

print(f"INFO: Django settings loaded. DEBUG={DEBUG}, ALLOWED_HOSTS={ALLOWED_HOSTS}, DB_ENGINE={DATABASES['default']['ENGINE']}")
if CORS_ALLOWED_ORIGINS:
    print(f"INFO: CORS Allowed Origins: {CORS_ALLOWED_ORIGINS}")
# else:
#     print(f"INFO: CORS Allow All Origins: {CORS_ALLOW_ALL_ORIGINS}")

# Configure MEDIA settings for file uploads
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media' # Using modern pathlib syntax

# Configure Celery and Celery Beat for scheduled tasks
# Make sure your broker URL is set correctly (e.g., for Redis or RabbitMQ)
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'


# --- LOGGING CONFIGURATION ---

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    # Formatters describe the layout of your log messages
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    # Handlers decide what to do with a log message (e.g., print to console, write to file)
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    # Loggers are the entry point. You send messages to a logger.
    "loggers": {
        # The root logger catches everything
        "root": {
            "handlers": ["console"],
            "level": "INFO", # Change to "DEBUG" to see ALL messages
        },
        # You can also configure loggers for specific apps
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "apps": { # This will catch logs from all of your custom apps
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": False,
        }
    },
}