# FILE: apps/features/uploader/api/urls.py

from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import FileUploadView, UploadedFileViewSet

# The router will automatically generate URLs for listing, retrieving, and deleting.
router = DefaultRouter()
router.register(r'files', UploadedFileViewSet, basename='uploadedfile')

urlpatterns = [
    # The dedicated endpoint for the multipart upload action
    path('upload/', FileUploadView.as_view(), name='file-upload'),

    # Include the URLs generated by the router for file management (list, retrieve, delete)
    path('', include(router.urls)),
]