"""
Django settings for main_backend project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import dotenv
import dj_database_url
from pathlib import Path
import logging.config # For potential logging setup later

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

PROJECT_ROOT = BASE_DIR.parent # Points to the 'omnicore-ai-platform' root directory

# --- Load Environment Variables ---
# Load .env file from the project root directory
ENV_FILE_PATH = PROJECT_ROOT / '.env'
if ENV_FILE_PATH.is_file():
    print(f"INFO: Loading environment variables from: {ENV_FILE_PATH}")
    dotenv.load_dotenv(dotenv_path=ENV_FILE_PATH)
else:
    print(f"WARNING: .env file not found at {ENV_FILE_PATH}. Using default settings or environment variables.")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', '!!!replace_this_with_a_default_only_for_local_dev_if_env_missing!!!')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'False').lower() in ('true', '1', 't')

ALLOWED_HOSTS_STRING = os.getenv('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1')
ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS_STRING.split(',') if host.strip()]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-Party Apps
    'rest_framework',        # Django REST Framework for APIs
    'corsheaders',           # For handling Cross-Origin Resource Sharing

    # Your Local Apps (Prefix with 'apps.' because they are inside the 'apps' folder)
    'apps.core_api',         # Shared logic/models if needed
    'apps.control_api',      # API for controlling Docker services
    # Add other apps here later ('apps.stt_api', 'apps.tts_api', etc.)
]

MIDDLEWARE = [
    # CORS Middleware should be placed high, especially before CommonMiddleware
    'corsheaders.middleware.CorsMiddleware',

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'main_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'main_backend.wsgi.application'


# --- Database Configuration ---
# https://docs.djangoproject.com/en/stable/ref/settings/#databases
# Uses dj-database-url to parse DATABASE_URL from .env
DATABASE_URL = os.getenv('DATABASE_URL')

if DATABASE_URL:
    print("INFO: Configuring database using DATABASE_URL from environment.")
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600, # Optional: connection pooling duration
            # Set ssl_require based on env var if needed for production managed DBs
            ssl_require=os.getenv('DB_SSL_REQUIRE', 'False').lower() in ('true', '1', 't')
        )
    }
else:
    # Fallback to SQLite only if DATABASE_URL is not set (for initial local setup without Docker/DB)
    # WARNING: This should NOT be used when running with Docker Compose setup as defined.
    print("WARNING: DATABASE_URL not set in environment. Falling back to SQLite3.")
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3', # Creates db file in 'backend' dir
        }
    }



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# --- Internationalization ---
# https://docs.djangoproject.com/en/stable/topics/i18n/
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True # Use timezone-aware datetimes


# --- Static files (CSS, JavaScript, Images) ---
# https://docs.djangoproject.com/en/stable/howto/static-files/
STATIC_URL = 'static/'
# Define STATIC_ROOT for collectstatic if you serve Django admin static files
# STATIC_ROOT = BASE_DIR / 'staticfiles_collected'


# --- Default primary key field type ---
# https://docs.djangoproject.com/en/stable/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# --- Django REST Framework Settings (Optional: Add defaults later) ---
REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    # 'DEFAULT_PERMISSION_CLASSES': [
    #     'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    # ],
    # Add authentication classes later if needed (e.g., JWT)
    # 'DEFAULT_AUTHENTICATION_CLASSES': [],
}


# --- CORS (Cross-Origin Resource Sharing) Settings ---
# Origins allowed to make requests to this backend
CORS_ALLOWED_ORIGINS_STRING = os.getenv('CORS_ALLOWED_ORIGINS', '')
CORS_ALLOWED_ORIGINS = [origin.strip() for origin in CORS_ALLOWED_ORIGINS_STRING.split(',') if origin.strip()]

# Alternatively, for development ONLY (less secure):
# CORS_ALLOW_ALL_ORIGINS = DEBUG # Allows all origins if DEBUG is True

# Allow cookies to be sent with requests (needed for sessions/CSRF if used)
CORS_ALLOW_CREDENTIALS = True

# You might need to whitelist headers if the frontend sends custom ones
# CORS_ALLOW_HEADERS = list(default_headers) + ['my-custom-header']


# --- Logging Configuration (Basic Example - Customize as needed) ---
# Simplest logging to console
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO', # Change to DEBUG for more verbose output
    },
    # Example: Quieter logging for noisy libraries
    # 'loggers': {
    #     'docker': {
    #         'handlers': ['console'],
    #         'level': 'INFO', # Docker library can be verbose on DEBUG
    #         'propagate': False,
    #     },
    # }
}

# Configure logging based on the settings dictionary
logging.config.dictConfig(LOGGING)

print(f"INFO: Django settings loaded. DEBUG={DEBUG}, ALLOWED_HOSTS={ALLOWED_HOSTS}, DB_ENGINE={DATABASES['default']['ENGINE']}")
if CORS_ALLOWED_ORIGINS:
    print(f"INFO: CORS Allowed Origins: {CORS_ALLOWED_ORIGINS}")
# else:
#     print(f"INFO: CORS Allow All Origins: {CORS_ALLOW_ALL_ORIGINS}")