# Generated by Django 5.2 on 2025-08-01 15:46

import apps.features.uploader.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=apps.features.uploader.models.get_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document')], max_length=10)),
                ('original_modified_at', models.DateTimeField(default=django.utils.timezone.now, help_text='The last modified timestamp of the original file.')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
